add text content in home
ThiagoLopes/uniso-semana-engenharia pull request #1
Opened 2017-10-21 21:53 UTC by EltonARodrigues

Texto de descrição adicionado no Home.html

2017-10-21 22:19 UTC, ThiagoLopes commented
Poderia adicionar a tag `trans`em cada paragrafo para futura internacionalização do site

2017-10-21 22:27 UTC, thiagolopes requested changes
@EltonARodrigues poderia adicionar a tag transem cada paragrafo para futura internacionalização do site

2017-10-21 22:27 UTC, ThiagoLopes commented on templates/home.html
> +            de novembro na Universidade de Sorocaba -  Câmpus Cidade Universitária Professor Aldo Vannucchi.
coloca um `<a>` com a localização de google maps

2017-10-21 22:27 UTC, ThiagoLopes commented on templates/home.html
> +            de novembro na Universidade de Sorocaba -  Câmpus Cidade Universitária Professor Aldo Vannucchi.
e um `a` com o [link](https://uniso.br)

2017-10-21 22:27 UTC, ThiagoLopes commented on templates/home.html
> +        <p> A Setima edição da Semana da Engenharia ocorre agora período de 10 de novembro a 17
use um `p` por linha.
não um `p` com `br`'s

2017-10-21 23:21 UTC, EltonARodrigues commented
Aplicada as modificações

2017-10-22 21:15 UTC, EltonARodrigues commented
corrigida a tradução dos links

2017-10-22 22:05 UTC, merged